repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.1.0"
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-shebang-scripts-are-executable
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: fix-byte-order-marker
  - repo: https://github.com/python-poetry/poetry
    rev: 'a358be7d4cfff6d0823d4e18f867654724b11596'
    hooks:
      - id: poetry-check
        name: poetry check
      - id: poetry-lock
        name: poetry lock
        args: [ "--no-update" ]
      - id: poetry-export
        name: poetry export (requirements.txt)
        args: [ "-f", "requirements.txt", "-o", "requirements.txt" ]
      - id: poetry-export
        name: poetry export (dev-requirements.txt)
        args: [ "--dev", "-f", "requirements.txt", "-o", "dev-requirements.txt" ]
  - repo: https://github.com/pycqa/flake8
    rev: "4.0.1"
    hooks:
      - id: flake8
