# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: "My Project"
site_url: "https://example.com/"
repo_url: https://github.com/abhabongse/python-project
nav:
  - Home: index.md
  - "API Reference":
    - ./api/index.md
    - "App Functions": ./api/app.md
    - "Helper Functions": ./api/helpers.md
theme:
  # More info: https://squidfunk.github.io/mkdocs-material/creating-your-site/
  name: material
  palette:
    scheme: slate
    primary: black
    accent: orange
  font:
    text: "IBM Plex Sans"
    code: "JetBrains Mono"
  icon:
    annotation: material/plus-circle-outline
  features:
    - content.code.copy
    - content.code.select
    - content.tooltips
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - search.suggest
    - search.highlight
# noinspection YAMLSchemaValidation
plugins:
  - glightbox
  - mkdocstrings:
      enabled: true
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            heading_level: 3
          import:
            - https://docs.python.org/3/objects.inv
  - search
  - social
# noinspection YAMLSchemaValidation
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      title: On this page
      permalink: true
extra_javascript:
  - ./javascripts/katex.js
  - https://cdn.jsdelivr.net/npm/katex@0.16/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16/dist/contrib/auto-render.min.js
extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16/dist/katex.min.css
