[project]
name = "My Project"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
license = "Apache-2.0"

[[project.authors]]
name = "Your Name"
email = "you@example.com"

[tool.sphinx-pyproject]
copyright = "2022, Your Name"
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx.ext.todo",
    "sphinx.ext.intersphinx",
    "sphinx.ext.autosectionlabel",
    "sphinx.ext.graphviz",
    "sphinx.ext.inheritance_diagram",
    "myst_parser",
]
templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

[tool.poetry]
# Duplicated from [project] section because poetry has not yet supported
name = "my-project"
version = "0.1.0"
description = ""
readme = "README.md"
license = "Apache-2.0"
authors = ["Your Name <you@example.com>"]

[[tool.poetry.packages]]
include = "myhelpers"
from = "src"

[[tool.poetry.packages]]
include = "myapp"
from = "src"

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.3"
more-itertools = "^8.14.0"
python-dotenv = "^0.21.0"
rich = "^12.5.1"
tomli = "^2.0.1"

[tool.poetry.group.docs.dependencies]
furo = ">=2022.6.21"
myst-parser = ">=0.18.0"
sphinx = ">=4.4.0"
sphinx-autobuild = ">=2021.3.14"
sphinx-pyproject = ">=0.1.0"

[tool.poetry.group.dev.dependencies]
coverage = "^6.4.4"
flake8 = "^5.0.4"
flake8-bugbear = "^22.9.11"
flake8-commas = "^2.1.0"
flake8-import-order = "^0.18.1"
jupyterlab = "^3.4.6"
pycodestyle = "^2.9.1"
pyflakes = "^2.5.0"
pytest = "^7.1.3"
pytest-cov = "^3.0.0"
pytest-icdiff = "^0.6"
pytest-sugar = "^0.9.5"
pytest-xdist = "^2.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
