version = 1
disable_existing_loggers = false

[loggers.root]
level = "DEBUG"
handlers = ["queue_handler"]

[handlers.queue_handler]
class = "logging.handlers.QueueHandler"
handlers = ["console", "rich", "rotating_files"]
respect_handler_level = true

[handlers.console]
level = "WARNING"
class = "logging.StreamHandler"
stream = "ext://sys.stderr"
formatter = "simple"

[handlers.rich]
"()" = "rich.logging.RichHandler"
log_time_format = "%Y-%m-%d %H:%M:%S"

[handlers.rotating_files]
level = "DEBUG"
class = "logging.handlers.RotatingFileHandler"
filename = "myapp.log.jsonl"
maxBytes = 1024
backupCount = 3
formatter = "json"

[formatters.simple]
format = "%(asctime)s [%(levelname)9s] %(message)s"
datefmt = "%Y-%m-%d %H:%M:%S"

[formatters.json]
"()" = "myhelpers.primitives.logging.JSONFormatter"
datefmt = "%Y-%m-%dT%H:%M:%S%z"
timezone = "Asia/Bangkok"
include_extra = "flatten"

[formatters.json.fields]
level = "levelname"
message = "message"
timestamp = "timestamp"
logger = "name"
module = "module"
function = "funcName"
line = "lineno"
thread_name = "threadName"
